Use vmmap for reading memory maps on macOS
Call to .memory_maps() fails on Azure pipelines with:

    Traceback (most recent call last):
        ...
        return cext.proc_memory_maps(self.pid)
    OSError: [Errno 22] Invalid argument

Also, support for memory_maps() has been removed for macOS starting
psutil-v5.6.x xref: https://github.com/giampaolo/psutil/issues/1291